FROM quay.io/aptible/ubuntu:14.04

# Install dependencies
RUN apt-install runit wget python-httplib2

ENV CB_RELEASE_URL=http://packages.couchbase.com/releases
ENV CB_VERSION=<%= ENV['CB_VERSION'] %>
ENV CB_PACKAGE=couchbase-server-enterprise_<%= ENV['CB_VERSION'] %>-ubuntu12.04_amd64.deb
ENV CB_SHA1SUM=<%= ENV['CB_SHA1SUM'] %>

ENV PATH=$PATH:/opt/couchbase/bin:/opt/couchbase/bin/tools:/opt/couchbase/bin/install
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/couchbase/lib

# Install couchbase
RUN wget -N $CB_RELEASE_URL/$CB_VERSION/$CB_PACKAGE && \
    echo "$CB_SHA1SUM  $CB_PACKAGE" | sha256sum -c - && \
    dpkg -i ./$CB_PACKAGE && rm -f ./$CB_PACKAGE

ADD ./bin/run-database.sh /usr/bin/
ADD ./bin/utilities.sh /usr/bin/

ENV DATA_DIRECTORY /var/db
VOLUME ["$DATA_DIRECTORY"]

ENV CONFIG_DIRECTORY /opt/couchbase/etc/couchdb/local.d
VOLUME ["$CONFIG_DIRECTORY"]

# 8091: Couchbase Web console, REST/HTTP interface
# 8092: Views, queries, XDCR
# 8093: Query services (4.0+)
# 9110: Full-text Serarch (4.5 DP; will be 8094 in 4.5+)
# 11207: Smart client library data node access (SSL)
# 11210: Smart client library/moxi data node access
# 11211: Legacy non-smart client library data node access
# 18091: Couchbase Web console, REST/HTTP interface (SSL)
# 18092: Views, query, XDCR (SSL)

# TODO: Expose all ports once --discover output is respected
# EXPOSE 8091 8092 8093 9110 11207 11210 11211 18091 18092
EXPOSE 8091

ENTRYPOINT ["run-database.sh"]
